apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
extenders:
  - urlPrefix: "http://augur-extender.augur.svc.cluster.local:8888"
    filterVerb: "filter"
    prioritizeVerb: "prioritize"
    weight: 10
    enableHTTPS: false
    httpTimeout: 5s
    nodeCacheCapable: false
    ignorable: true  # fall back to default scoring if extender is unavailable
