// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/augur.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeFeatures describes the numeric feature vector for a single node.
type NodeFeatures struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeName        string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	CpuCapacity     float64                `protobuf:"fixed64,2,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	CpuAvailable    float64                `protobuf:"fixed64,3,opt,name=cpu_available,json=cpuAvailable,proto3" json:"cpu_available,omitempty"`
	MemoryCapacity  float64                `protobuf:"fixed64,4,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	MemoryAvailable float64                `protobuf:"fixed64,5,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	GpuCount        float64                `protobuf:"fixed64,6,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	PodCount        float64                `protobuf:"fixed64,7,opt,name=pod_count,json=podCount,proto3" json:"pod_count,omitempty"`
	PodCapacity     float64                `protobuf:"fixed64,8,opt,name=pod_capacity,json=podCapacity,proto3" json:"pod_capacity,omitempty"`
	CostPerHour     float64                `protobuf:"fixed64,9,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	Zone            float64                `protobuf:"fixed64,10,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeFeatures) Reset() {
	*x = NodeFeatures{}
	mi := &file_proto_augur_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFeatures) ProtoMessage() {}

func (x *NodeFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_augur_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFeatures.ProtoReflect.Descriptor instead.
func (*NodeFeatures) Descriptor() ([]byte, []int) {
	return file_proto_augur_proto_rawDescGZIP(), []int{0}
}

func (x *NodeFeatures) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeFeatures) GetCpuCapacity() float64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *NodeFeatures) GetCpuAvailable() float64 {
	if x != nil {
		return x.CpuAvailable
	}
	return 0
}

func (x *NodeFeatures) GetMemoryCapacity() float64 {
	if x != nil {
		return x.MemoryCapacity
	}
	return 0
}

func (x *NodeFeatures) GetMemoryAvailable() float64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *NodeFeatures) GetGpuCount() float64 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *NodeFeatures) GetPodCount() float64 {
	if x != nil {
		return x.PodCount
	}
	return 0
}

func (x *NodeFeatures) GetPodCapacity() float64 {
	if x != nil {
		return x.PodCapacity
	}
	return 0
}

func (x *NodeFeatures) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

func (x *NodeFeatures) GetZone() float64 {
	if x != nil {
		return x.Zone
	}
	return 0
}

// ScoreRequest is sent from the Go extender to the Python RL agent.
type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`
	Nodes         []*NodeFeatures        `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_proto_augur_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_augur_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_augur_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ScoreRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScoreRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ScoreRequest) GetNodes() []*NodeFeatures {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// NodeScore pairs a node name with the agent's predicted score.
type NodeScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScore) Reset() {
	*x = NodeScore{}
	mi := &file_proto_augur_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScore) ProtoMessage() {}

func (x *NodeScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_augur_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScore.ProtoReflect.Descriptor instead.
func (*NodeScore) Descriptor() ([]byte, []int) {
	return file_proto_augur_proto_rawDescGZIP(), []int{2}
}

func (x *NodeScore) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// ScoreResponse returns per-node scores from the RL agent.
type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeScores    []*NodeScore           `protobuf:"bytes,1,rep,name=node_scores,json=nodeScores,proto3" json:"node_scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_augur_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_augur_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_augur_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreResponse) GetNodeScores() []*NodeScore {
	if x != nil {
		return x.NodeScores
	}
	return nil
}

var File_proto_augur_proto protoreflect.FileDescriptor

const file_proto_augur_proto_rawDesc = "" +
	"\n" +
	"\x11proto/augur.proto\x12\x05augur\"\xdc\x02\n" +
	"\fNodeFeatures\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\fcpu_capacity\x18\x02 \x01(\x01R\vcpuCapacity\x12#\n" +
	"\rcpu_available\x18\x03 \x01(\x01R\fcpuAvailable\x12'\n" +
	"\x0fmemory_capacity\x18\x04 \x01(\x01R\x0ememoryCapacity\x12)\n" +
	"\x10memory_available\x18\x05 \x01(\x01R\x0fmemoryAvailable\x12\x1b\n" +
	"\tgpu_count\x18\x06 \x01(\x01R\bgpuCount\x12\x1b\n" +
	"\tpod_count\x18\a \x01(\x01R\bpodCount\x12!\n" +
	"\fpod_capacity\x18\b \x01(\x01R\vpodCapacity\x12\"\n" +
	"\rcost_per_hour\x18\t \x01(\x01R\vcostPerHour\x12\x12\n" +
	"\x04zone\x18\n" +
	" \x01(\x01R\x04zone\"\x8a\x01\n" +
	"\fScoreRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\x12)\n" +
	"\x05nodes\x18\x04 \x03(\v2\x13.augur.NodeFeaturesR\x05nodes\">\n" +
	"\tNodeScore\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"B\n" +
	"\rScoreResponse\x121\n" +
	"\vnode_scores\x18\x01 \x03(\v2\x10.augur.NodeScoreR\n" +
	"nodeScores2@\n" +
	"\n" +
	"AugurAgent\x122\n" +
	"\x05Score\x12\x13.augur.ScoreRequest\x1a\x14.augur.ScoreResponseB\"Z github.com/mnorrsken/augur/protob\x06proto3"

var (
	file_proto_augur_proto_rawDescOnce sync.Once
	file_proto_augur_proto_rawDescData []byte
)

func file_proto_augur_proto_rawDescGZIP() []byte {
	file_proto_augur_proto_rawDescOnce.Do(func() {
		file_proto_augur_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_augur_proto_rawDesc), len(file_proto_augur_proto_rawDesc)))
	})
	return file_proto_augur_proto_rawDescData
}

var file_proto_augur_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_augur_proto_goTypes = []any{
	(*NodeFeatures)(nil),  // 0: augur.NodeFeatures
	(*ScoreRequest)(nil),  // 1: augur.ScoreRequest
	(*NodeScore)(nil),     // 2: augur.NodeScore
	(*ScoreResponse)(nil), // 3: augur.ScoreResponse
}
var file_proto_augur_proto_depIdxs = []int32{
	0, // 0: augur.ScoreRequest.nodes:type_name -> augur.NodeFeatures
	2, // 1: augur.ScoreResponse.node_scores:type_name -> augur.NodeScore
	1, // 2: augur.AugurAgent.Score:input_type -> augur.ScoreRequest
	3, // 3: augur.AugurAgent.Score:output_type -> augur.ScoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_augur_proto_init() }
func file_proto_augur_proto_init() {
	if File_proto_augur_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_augur_proto_rawDesc), len(file_proto_augur_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_augur_proto_goTypes,
		DependencyIndexes: file_proto_augur_proto_depIdxs,
		MessageInfos:      file_proto_augur_proto_msgTypes,
	}.Build()
	File_proto_augur_proto = out.File
	file_proto_augur_proto_goTypes = nil
	file_proto_augur_proto_depIdxs = nil
}
