// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/augur.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AugurAgent_Score_FullMethodName = "/augur.AugurAgent/Score"
)

// AugurAgentClient is the client API for AugurAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AugurAgent is the gRPC service exposed by the Python RL agent.
type AugurAgentClient interface {
	// Score takes cluster state and returns per-node placement scores.
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type augurAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAugurAgentClient(cc grpc.ClientConnInterface) AugurAgentClient {
	return &augurAgentClient{cc}
}

func (c *augurAgentClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, AugurAgent_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AugurAgentServer is the server API for AugurAgent service.
// All implementations must embed UnimplementedAugurAgentServer
// for forward compatibility.
//
// AugurAgent is the gRPC service exposed by the Python RL agent.
type AugurAgentServer interface {
	// Score takes cluster state and returns per-node placement scores.
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedAugurAgentServer()
}

// UnimplementedAugurAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAugurAgentServer struct{}

func (UnimplementedAugurAgentServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedAugurAgentServer) mustEmbedUnimplementedAugurAgentServer() {}
func (UnimplementedAugurAgentServer) testEmbeddedByValue()                    {}

// UnsafeAugurAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AugurAgentServer will
// result in compilation errors.
type UnsafeAugurAgentServer interface {
	mustEmbedUnimplementedAugurAgentServer()
}

func RegisterAugurAgentServer(s grpc.ServiceRegistrar, srv AugurAgentServer) {
	// If the following call panics, it indicates UnimplementedAugurAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AugurAgent_ServiceDesc, srv)
}

func _AugurAgent_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AugurAgentServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AugurAgent_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AugurAgentServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AugurAgent_ServiceDesc is the grpc.ServiceDesc for AugurAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AugurAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "augur.AugurAgent",
	HandlerType: (*AugurAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _AugurAgent_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/augur.proto",
}
